Import('env')
Import('libs')

env['LIBPATH'] = ['#/tnp', '#/lib/libtommath', '#/lib/libtomcrypt']
env['CPPPATH'] = ['#/tnp/include', '#/platform_library']

server_files = Glob('server_*.cpp')
env.Build('Program', 'server', server_files, LIBS_CFG=libs[1])

client_files = Glob('client_*.cpp')
env.Build('Program', 'client', client_files, LIBS_CFG=libs[1])
