Import('env')

files = Glob('src/*.cpp')
env['CPPPATH'] = ['#/platform_library/', '#/lib/libtommath', '#/lib/libtomcrypt/src/headers', '#/tnp/include']
env['LIBPATH'] = ['#/lib/libtommath', '#/lib/libtomcrypt']
env['LIBS'] = ['libtommath', 'libtomcrypt']

ret = env.Build('StaticLibrary', 'tnp', files)
Return('ret')
